### ISSUE TITLE
Past images missing

### ISSUE THREAD

**Issue by chloester** [wanderingstan/Lifeslice#6]
![Screen Shot 2013-01-24 at 2 44 54 PM](https://f.cloud.github.com/assets/495410/95633/bd8f5460-6677-11e2-96a6-fc0e0e98d51d.png)
About half of my thumbnails are not showing up, even though they appear in the popup when I click on them. Not sure what the cause is.

**Comment by wanderingstan** [comment]
Assuming this is now fixed...
