### ISSUE TITLE
Day view in Lifereport doesn't show any data

### ISSUE THREAD

**Issue by zacharyabresch** [wanderingstan/Lifeslice#9]
I really like the idea behind this app. Unfortunately, when I view the Lifereport I can't see any data on the daily views. The monthly view seems to show the webcam shots but when I click on a specific day no data is displayed. I've checked all the boxes, clicked all the radio buttons and have not been able to get it to work.

I'm running Mavericks (OSX 10.9). It looks as if issue #8 might be related but I installed the app after I upgraded.

**Comment by adamthede** [comment]
Hi @wanderingstan !  All seems to work for me!  Thanks!

**Comment by sesam** [comment]
Works for me too :)

**Comment by wanderingstan** [comment]
Finally got to the bottom of this issue: If user was NOT recording location data, the day-view display would crash upon hitting the empty location array. This is now fixed and committed, and will be in the 2.22 release going out soon.

**Comment by zacharyabresch** [comment]
Late to the game but things seem to be working for me too! Cheers! :+1:
